### ISSUE TITLE
Is this still the repo?

### ISSUE THREAD

**Issue by groovecoder** [vtoubiana/TrackMeNot#50]
Is this still the repo for TrackMeNot? There's very little activity here and it's a jpm code-base so I assume it's not the code-base for the Chrome extension?

**Comment by vtoubiana** [comment]
Indeed I was not able to work on the project for a while but should resume soon. The Chrome repo is here: https://github.com/vtoubiana/TrackMeNot-Chrome

**Comment by groovecoder** [comment]
Firefox now supports WebExtension add-ons, so you may be able to combine the 2 code-bases into a single repo that builds both extensions.

**Comment by vtoubiana** [comment]
Thanks, I started to do that about 6 months ago but then some API were not supported I think. I'll combine the codes ASAP.

**Comment by vtoubiana** [comment]
I have commited the Web extension version. I'll do some testing before pushing the update.

**Comment by vtoubiana** [comment]
Quick question @groovecoder: do you know if there is a neat way to have the same code used for the Firefox/Opera extension and for Chrome? As far as I can tell the main remain difference remaining is the
API  Namespace: use "browser" instead of "chrome". This could be solved by checking "if (chrome == undefined) { api = browser} else { api= chrome} but there might be a better way.

Thank you,

Vincent

**Comment by groovecoder** [comment]
You should be able to use `chrome` in Firefox as well.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities

In many cases, Chrome code-bases "Just Work" in Firefox.
